package repository

import (
	"context"
	"fmt"
	"regexp"
	"strings"
	"testing"

	"crm-backend/internal/domain"

	"github.com/google/uuid"
	"gorm.io/driver/postgres"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"
)

// The builder is pure, so these tests run without a database (unlike the
// Docker-backed integration tests, nothing here skips in -short mode).

var (
	testOrgID  = uuid.MustParse("11111111-1111-1111-1111-111111111111")
	testUserID = uuid.MustParse("22222222-2222-2222-2222-222222222222")
	testDefID  = uuid.MustParse("33333333-3333-3333-3333-333333333333")
)

func dealRef() reportTableRef {
	return reportTableRef{Table: "deals", JSONColumn: "custom_fields"}
}

// customRef mirrors reportRefForDef exactly, Slug included. It used to omit the
// slug, which silently disabled the row predicate in every test that used it —
// see TestBuildReportSQL_RowPredicateAppliesToCustomObjects.
func customRef() reportTableRef {
	id := testDefID
	return reportTableRef{Table: "custom_object_records", JSONColumn: "data", ObjectDefID: &id, Slug: "property"}
}

func companyRef() reportTableRef {
	return reportTableRef{Table: "companies", JSONColumn: "custom_fields", Slug: "company"}
}

func taskRef() reportTableRef {
	return reportTableRef{Table: "tasks", Slug: "task"}
}

func activityRef() reportTableRef {
	return reportTableRef{Table: "activities", Slug: "activity"}
}

func dealCatalog() []domain.ReportField {
	return []domain.ReportField{
		{Key: "title", Label: "Title", Type: "text", Column: "title"},
		{Key: "value", Label: "Value", Type: "number", Column: "value"},
		{Key: "stage", Label: "Stage", Type: "relation", Column: "stage_id", LabelKind: "stage"},
		{Key: "owner_user_id", Label: "Owner", Type: "relation", Column: "owner_user_id", LabelKind: "user"},
		{Key: "is_won", Label: "Won", Type: "boolean", Column: "is_won"},
		{Key: "closed_at", Label: "Closed", Type: "date", Column: "closed_at"},
		{Key: "created_at", Label: "Created", Type: "date", Column: "created_at"},
		{Key: "priority", Label: "Priority", Type: "select", JSONKey: "priority", Options: []string{"low", "high"}},
	}
}

func customCatalog() []domain.ReportField {
	return []domain.ReportField{
		{Key: "status", Label: "Status", Type: "select", JSONKey: "status"},
		{Key: "sqft", Label: "Sq Ft", Type: "number", JSONKey: "sqft"},
		{Key: "listed_on", Label: "Listed", Type: "date", JSONKey: "listed_on"},
		{Key: "created_at", Label: "Created", Type: "date", Column: "created_at"},
	}
}

func TestBuildReportSQL_TypedTableGroupsWithOwnScope(t *testing.T) {
	cfg := domain.ReportConfig{
		Chart: domain.ReportChartLine,
		Filters: &domain.ReportFilterGroup{
			Op:    "AND",
			Rules: []domain.ReportFilterRule{{Field: "is_won", Operator: "eq", Value: true}},
		},
		GroupBy:   &domain.ReportGroupBy{Field: "closed_at", Bucket: "month"},
		Aggregate: &domain.ReportAggregate{Fn: "sum", Field: "value"},
	}
	roleID := uuid.MustParse("33333333-3333-3333-3333-333333333333")
	q, args, err := buildReportSQL(dealRef(), dealCatalog(), cfg, testOrgID,
		reportScope{Scope: domain.DataScopeOwn, UserID: testUserID, RoleID: roleID})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// The row predicate is not pinned as a golden string — it is generated by
	// RecordAccessPredicate (covered directly in access_predicate_test.go) and would
	// make this test fail on every widening of the share model. What matters HERE is
	// that a report applies the same restriction the list pages do, and applies it
	// alongside the config's own filters.
	for _, frag := range []string{
		"FROM deals WHERE deals.org_id = ? AND deals.deleted_at IS NULL",
		"deals.owner_user_id = ?",
		"FROM record_shares rs",
		"rs.target_type = 'role'",
		"(deals.is_won = ?)",
		"GROUP BY 1 ORDER BY 1 ASC NULLS LAST LIMIT 100",
	} {
		if !strings.Contains(q, frag) {
			t.Errorf("query missing %q:\n%s", frag, q)
		}
	}

	// The caller's own identity must be bound, and the record_shares match must be
	// discriminated by the deal slug.
	wantArgs := []any{testOrgID, testUserID, "deal", testOrgID, testUserID, roleID, testUserID, testOrgID, true}
	if len(args) != len(wantArgs) {
		t.Fatalf("args = %v, want %v", args, wantArgs)
	}
	for i := range wantArgs {
		if args[i] != wantArgs[i] {
			t.Errorf("arg[%d] = %v, want %v", i, args[i], wantArgs[i])
		}
	}
}

// An 'all'-scoped caller gets no row predicate at all — only org + soft-delete.
func TestBuildReportSQL_AllScopeHasNoRowPredicate(t *testing.T) {
	cfg := domain.ReportConfig{
		Chart:     domain.ReportChartBar,
		GroupBy:   &domain.ReportGroupBy{Field: "closed_at", Bucket: "month"},
		Aggregate: &domain.ReportAggregate{Fn: "count"},
	}
	q, _, err := buildReportSQL(dealRef(), dealCatalog(), cfg, testOrgID,
		reportScope{Scope: domain.DataScopeAll, UserID: testUserID})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if strings.Contains(q, "record_shares") || strings.Contains(q, "owner_user_id") {
		t.Errorf("an all-scoped report must carry no row predicate:\n%s", q)
	}
}

// A team-scoped report must reach teammates' rows — the same widening the list
// pages get. Before U6 a report and a list page could disagree, because each
// carried its own copy of the predicate.
func TestBuildReportSQL_TeamScopeReachesTeammates(t *testing.T) {
	cfg := domain.ReportConfig{
		Chart:     domain.ReportChartBar,
		GroupBy:   &domain.ReportGroupBy{Field: "closed_at", Bucket: "month"},
		Aggregate: &domain.ReportAggregate{Fn: "count"},
	}
	q, _, err := buildReportSQL(dealRef(), dealCatalog(), cfg, testOrgID,
		reportScope{Scope: domain.DataScopeTeam, UserID: testUserID})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(q, "user_group_members m1") {
		t.Errorf("a team-scoped report must include the teammate predicate:\n%s", q)
	}
}

func TestBuildReportSQL_JSONBCustomObject(t *testing.T) {
	cfg := domain.ReportConfig{
		Chart: domain.ReportChartBar,
		Filters: &domain.ReportFilterGroup{
			Op:    "AND",
			Rules: []domain.ReportFilterRule{{Field: "sqft", Operator: "gt", Value: float64(2000)}},
		},
		GroupBy:   &domain.ReportGroupBy{Field: "status"},
		Aggregate: &domain.ReportAggregate{Fn: "count"},
	}
	q, args, err := buildReportSQL(customRef(), customCatalog(), cfg, testOrgID, reportScope{Scope: domain.DataScopeAll, UserID: uuid.Nil})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	want := "SELECT custom_object_records.data->>'status' AS group_key, COUNT(*) AS agg_value, COUNT(*) AS row_count " +
		"FROM custom_object_records WHERE custom_object_records.org_id = ? AND custom_object_records.deleted_at IS NULL AND custom_object_records.object_def_id = ? AND " +
		`((CASE WHEN custom_object_records.data->>'sqft' ~ '^-{0,1}[0-9]+(\.[0-9]+){0,1}$' THEN (custom_object_records.data->>'sqft')::numeric END) > ?) ` +
		"GROUP BY 1 ORDER BY agg_value DESC NULLS LAST LIMIT 100"
	if q != want {
		t.Errorf("query mismatch:\n got: %s\nwant: %s", q, want)
	}
	if len(args) != 3 || args[0] != testOrgID || args[1] != testDefID || args[2] != float64(2000) {
		t.Errorf("args = %v", args)
	}
}

// Companies are the one genuinely ownerless object: org-wide, no owner column,
// never a record_shares target. A row predicate there would be wrong, and it
// must not appear just because the table is unfamiliar.
func TestBuildReportSQL_CompaniesHaveNoRowPredicate(t *testing.T) {
	cfg := domain.ReportConfig{
		Chart:     domain.ReportChartBar,
		GroupBy:   &domain.ReportGroupBy{Field: "industry"},
		Aggregate: &domain.ReportAggregate{Fn: "count"},
	}
	catalog := []domain.ReportField{{Key: "industry", Label: "Industry", Type: "text", Column: "industry"}}
	q, _, err := buildReportSQL(companyRef(), catalog, cfg, testOrgID, reportScope{Scope: domain.DataScopeOwn, UserID: testUserID})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if strings.Contains(q, "owner_user_id") || strings.Contains(q, "record_shares") {
		t.Errorf("own-scope predicate leaked onto companies: %s", q)
	}
}

// Custom objects DO get the row predicate. They have carried owner_user_id since
// U6.3 (migration 000039) and reportRefForDef always populates Slug, so a report
// over a custom object is row-scoped exactly like its list page.
//
// This assertion replaces one that claimed the opposite. That test passed only
// because its fixture omitted Slug, which made the old rowPredicateFor fall into
// its `recordType == ""` arm and drop the predicate — the fail-open default this
// file's control test now forbids.
func TestBuildReportSQL_RowPredicateAppliesToCustomObjects(t *testing.T) {
	cfg := domain.ReportConfig{
		Chart:     domain.ReportChartBar,
		GroupBy:   &domain.ReportGroupBy{Field: "status"},
		Aggregate: &domain.ReportAggregate{Fn: "count"},
	}
	q, args, err := buildReportSQL(customRef(), customCatalog(), cfg, testOrgID, reportScope{Scope: domain.DataScopeOwn, UserID: testUserID})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(q, "custom_object_records.owner_user_id = ?") {
		t.Errorf("own-scope report over a custom object must filter by owner:\n%s", q)
	}
	if !strings.Contains(q, "record_shares") {
		t.Errorf("own-scope report over a custom object must honour shares:\n%s", q)
	}
	// The share discriminator is the object SLUG, not the table — every custom
	// object lives in one table, so the wrong value here would cross-match.
	var sawSlug bool
	for _, a := range args {
		if s, ok := a.(string); ok && s == "property" {
			sawSlug = true
		}
	}
	if !sawSlug {
		t.Errorf("record_shares.record_type must bind the object slug; args = %v", args)
	}
}

// ============================================================
// R9.5 — the fail-closed row predicate
// ============================================================

// rowPredicateFor used to return ("", nil) for any table it did not recognize,
// which meant a newly reportable table shipped with org_id + deleted_at as its
// ONLY filter: every row-scoped rep reading the whole org, silently. This test
// fails the moment that default comes back.
func TestRowPredicateFor_UnknownTableIsAnError(t *testing.T) {
	ref := reportTableRef{Table: "refresh_tokens", Slug: "refresh_token"}
	sql, args, err := rowPredicateFor(ref, testOrgID, reportScope{Scope: domain.DataScopeOwn, UserID: testUserID})
	if err == nil {
		t.Fatalf("an unrecognized table must be an error, not an unfiltered report (got sql=%q args=%v)", sql, args)
	}
	if !strings.Contains(err.Error(), "refresh_tokens") {
		t.Errorf("the error should name the table: %v", err)
	}
	// "report:"-prefixed errors are what the usecase turns into a 400 rather
	// than a 500, so the operator sees a broken report instead of a stack trace.
	if !strings.HasPrefix(err.Error(), "report:") {
		t.Errorf("error must carry the report: prefix, got %q", err.Error())
	}
}

// A custom object with no slug cannot be row-scoped (record_shares has nothing
// to match on), so it must fail rather than run unfiltered.
func TestRowPredicateFor_CustomObjectWithoutSlugIsAnError(t *testing.T) {
	id := testDefID
	ref := reportTableRef{Table: "custom_object_records", JSONColumn: "data", ObjectDefID: &id}
	if _, _, err := rowPredicateFor(ref, testOrgID, reportScope{Scope: domain.DataScopeOwn, UserID: testUserID}); err == nil {
		t.Fatal("a slugless custom object must be an error")
	}
}

// An org is free to name a CUSTOM object "task". Its rows live in
// custom_object_records, so it must be dispatched by object_def_id — dispatching
// on the slug would emit `tasks.assigned_to` against the wrong table.
func TestRowPredicateFor_CustomObjectSlugCannotHijackReportOnlyObject(t *testing.T) {
	id := testDefID
	ref := reportTableRef{Table: "custom_object_records", JSONColumn: "data", ObjectDefID: &id, Slug: "task"}
	sql, _, err := rowPredicateFor(ref, testOrgID, reportScope{Scope: domain.DataScopeOwn, UserID: testUserID})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if strings.Contains(sql, "tasks.") {
		t.Errorf("a custom object slugged 'task' must not be scoped as the tasks table:\n%s", sql)
	}
	if !strings.Contains(sql, "custom_object_records.owner_user_id") {
		t.Errorf("expected the custom-object predicate:\n%s", sql)
	}
}

// Every declared report-only object must have a row-access arm. Adding a
// descriptor without one is the exact mistake the fail-closed default exists to
// catch, and this catches it at build time instead of at runtime.
func TestRowPredicateFor_EveryReportOnlyObjectHasAnArm(t *testing.T) {
	for _, ro := range domain.ReportOnlyObjects {
		ref := reportTableRef{Table: ro.Table, Slug: ro.Slug}
		sql, _, err := rowPredicateFor(ref, testOrgID, reportScope{Scope: domain.DataScopeOwn, UserID: testUserID})
		if err != nil {
			t.Fatalf("%s: no row-access arm in rowPredicateFor: %v", ro.Slug, err)
		}
		if sql == "" {
			t.Fatalf("%s: row-scoped caller got an EMPTY predicate — that is an org-wide read", ro.Slug)
		}
		// The rule must be the shared one, not an ad-hoc rewrite: both consumers
		// reach contacts/deals through the same EXISTS subqueries.
		if !strings.Contains(sql, "record_shares") {
			t.Errorf("%s: predicate ignores shares:\n%s", ro.Slug, sql)
		}
	}
}

// pgPlaceholderRe matches gorm's rendered bind markers ($1, $2, …).
var pgPlaceholderRe = regexp.MustCompile(`\$\d+`)

// dryRunDB builds SQL without a database. gorm's DryRun renders the full
// statement — text AND bind values — into Statement, which is what lets the
// parity test below compare against what the LIST PAGE actually runs rather
// than against the helper the report builder happens to call.
//
// sql.Open is lazy and DisableAutomaticPing stops gorm from dialling, so the
// unroutable DSN is never contacted; this runs in -short mode with no Docker.
func dryRunDB(t *testing.T) *gorm.DB {
	t.Helper()
	db, err := gorm.Open(
		postgres.New(postgres.Config{DSN: "postgres://u:p@127.0.0.1:1/none?sslmode=disable"}),
		&gorm.Config{DryRun: true, DisableAutomaticPing: true, Logger: logger.Default.LogMode(logger.Silent)},
	)
	if err != nil {
		t.Fatalf("dry-run gorm: %v", err)
	}
	return db
}

// The report and the list page must apply the SAME rule — that is the entire
// reason TaskAccessPredicate/ActivityAccessPredicate exist as shared functions
// instead of a second copy.
//
// This compares the report builder's output against the statement taskScope and
// activityScope actually produce, bind values included. An earlier version of
// this test compared rowPredicateFor against the predicate helper DIRECTLY,
// which was tautological: swapping UserID and RoleID inside rowPredicateFor's
// arm produces byte-identical SQL and the same arg COUNT, so it passed while a
// rep saw rows scoped to their role id.
func TestReportPredicateMatchesListPagePredicate(t *testing.T) {
	roleID := uuid.MustParse("44444444-4444-4444-4444-444444444444")
	ctx := WithCallerScope(context.Background(), domain.DataScopeOwn, testUserID, roleID)

	for _, tc := range []struct {
		name    string
		ref     reportTableRef
		catalog []domain.ReportField
		listSQL func(*gorm.DB) *gorm.Statement
	}{
		{
			name: "task", ref: taskRef(),
			catalog: domain.ReportOnlyObjectBySlug("task").Catalog(),
			listSQL: func(db *gorm.DB) *gorm.Statement {
				var out []domain.Task
				return taskScope(db, ctx, testOrgID).Find(&out).Statement
			},
		},
		{
			name: "activity", ref: activityRef(),
			catalog: domain.ReportOnlyObjectBySlug("activity").Catalog(),
			listSQL: func(db *gorm.DB) *gorm.Statement {
				var out []domain.Activity
				return activityScope(db, ctx, testOrgID).Find(&out).Statement
			},
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			stmt := tc.listSQL(dryRunDB(t))
			listQuery, listArgs := stmt.SQL.String(), stmt.Vars

			// A table-mode report with no filters, so its args are exactly
			// [orgID] + the row predicate's — the same shape taskScope produces.
			_, reportArgs, err := buildReportSQL(tc.ref, tc.catalog, domain.ReportConfig{
				Chart: domain.ReportChartTable, Columns: []string{"created_at"},
			}, testOrgID, reportScope{Scope: domain.DataScopeOwn, UserID: testUserID, RoleID: roleID})
			if err != nil {
				t.Fatalf("report SQL: %v", err)
			}

			if len(reportArgs) != len(listArgs) {
				t.Fatalf("report binds %d args, the list page binds %d:\nreport=%v\nlist  =%v",
					len(reportArgs), len(listArgs), reportArgs, listArgs)
			}
			// The VALUES are the point. Identical SQL with user and role
			// transposed is the failure this catches.
			for i := range reportArgs {
				if fmt.Sprint(reportArgs[i]) != fmt.Sprint(listArgs[i]) {
					t.Errorf("bind arg %d differs — report=%v list=%v\nreport=%v\nlist  =%v",
						i, reportArgs[i], listArgs[i], reportArgs, listArgs)
				}
			}

			// And the predicate TEXT must be the one the list page runs.
			predSQL, _, err := rowPredicateFor(tc.ref, testOrgID,
				reportScope{Scope: domain.DataScopeOwn, UserID: testUserID, RoleID: roleID})
			if err != nil {
				t.Fatalf("rowPredicateFor: %v", err)
			}
			// gorm renders the numbered form ($1, $2, …); the builder emits `?`.
			// Normalise before comparing, otherwise this can only ever fail.
			if !strings.Contains(pgPlaceholderRe.ReplaceAllString(listQuery, "?"), predSQL) {
				t.Errorf("the list page does not run the report's predicate.\npredicate: %s\nlist page: %s", predSQL, listQuery)
			}
		})
	}
}

// An 'all'-scoped caller reads the whole org, so no predicate at all — the same
// short-circuit the list pages take.
func TestReportOnlyPredicates_AllScopeIsUnrestricted(t *testing.T) {
	for _, ro := range domain.ReportOnlyObjects {
		ref := reportTableRef{Table: ro.Table, Slug: ro.Slug}
		sql, _, err := rowPredicateFor(ref, testOrgID, reportScope{Scope: domain.DataScopeAll, UserID: testUserID})
		if err != nil {
			t.Fatalf("%s: unexpected error: %v", ro.Slug, err)
		}
		if sql != "" {
			t.Errorf("%s: an all-scoped caller must carry no row predicate:\n%s", ro.Slug, sql)
		}
	}
}

// Neither table has owner_user_id. RecordAccessArgs defaults OwnerColumn to it,
// so a descriptor wired through the generic predicate by mistake would emit
// `tasks.owner_user_id` and 500 at runtime — after passing every unit test that
// only inspects SQL text for the word "predicate".
func TestReportOnlyPredicates_NeverReferenceOwnerUserIDOnTheirOwnTable(t *testing.T) {
	for _, ro := range domain.ReportOnlyObjects {
		ref := reportTableRef{Table: ro.Table, Slug: ro.Slug}
		sql, _, err := rowPredicateFor(ref, testOrgID, reportScope{Scope: domain.DataScopeOwn, UserID: testUserID})
		if err != nil {
			t.Fatalf("%s: unexpected error: %v", ro.Slug, err)
		}
		if strings.Contains(sql, ro.Table+".owner_user_id") {
			t.Errorf("%s has no owner_user_id column:\n%s", ro.Table, sql)
		}
	}
}

// Every report-only field must map to a NATIVE column. reportRefForDef hardcodes
// JSONColumn: "custom_fields" for every table-storage def, and neither tasks nor
// activities has that column — a JSONKey field would emit
// `tasks.custom_fields->>'x'` and fail at runtime.
func TestReportOnlyDescriptors_AllFieldsHaveNativeColumn(t *testing.T) {
	for _, ro := range domain.ReportOnlyObjects {
		if len(ro.Fields) == 0 {
			t.Errorf("%s declares no fields", ro.Slug)
		}
		for _, f := range ro.Fields {
			if f.Column == "" {
				t.Errorf("%s.%s has no Column — report-only objects have no JSONB blob", ro.Slug, f.Key)
			}
			if f.JSONKey != "" {
				t.Errorf("%s.%s sets JSONKey", ro.Slug, f.Key)
			}
			if !reportIdentRe.MatchString(f.Column) {
				t.Errorf("%s.%s column %q fails the identifier whitelist", ro.Slug, f.Key, f.Column)
			}
			// LabelKind "user" resolves without an OLS check (canResolveLabels);
			// anything else routes through Authorize against a slug, and an
			// invented kind renders "(Unknown)" with no error anywhere.
			if f.LabelKind != "" && f.LabelKind != "user" {
				t.Errorf("%s.%s uses LabelKind %q — only 'user' is wired up for report-only objects", ro.Slug, f.Key, f.LabelKind)
			}
		}
		if !reportIdentRe.MatchString(ro.Table) {
			t.Errorf("%s table %q fails the identifier whitelist", ro.Slug, ro.Table)
		}
	}
}

// The two templates shipped with R9.5 must actually compile. Both group by a
// user relation and filter on a column, so this is the end-to-end check that the
// descriptors, the operators and the row predicate agree.
func TestBuildReportSQL_ReportOnlyTemplatesCompile(t *testing.T) {
	activity := domain.ReportOnlyObjectBySlug("activity")
	if activity == nil {
		t.Fatal("activity descriptor missing")
	}
	cfg := domain.ReportConfig{
		Chart:     domain.ReportChartBar,
		GroupBy:   &domain.ReportGroupBy{Field: "user_id"},
		Aggregate: &domain.ReportAggregate{Fn: "count"},
		Filters: &domain.ReportFilterGroup{
			Op:    "AND",
			Rules: []domain.ReportFilterRule{{Field: "type", Operator: "neq", Value: "stage_change"}},
		},
	}
	q, _, err := buildReportSQL(activityRef(), activity.Catalog(), cfg, testOrgID,
		reportScope{Scope: domain.DataScopeOwn, UserID: testUserID})
	if err != nil {
		t.Fatalf("activities-per-rep failed to compile: %v", err)
	}
	if !strings.Contains(q, "activities.user_id") || !strings.Contains(q, "activities.type") {
		t.Errorf("unexpected SQL:\n%s", q)
	}

	// activities.type is a Postgres ENUM. Every operator must go through the
	// ::text cast — the emptiness ones in particular, because they compare
	// against the literal '' and Postgres rejects that as an enum label rather
	// than returning false. This is a runtime 500 reachable from the builder's
	// "Type — is empty" option, so it must be pinned per operator.
	for _, op := range []string{"eq", "neq", "in", "is_empty", "is_not_empty"} {
		rule := domain.ReportFilterRule{Field: "type", Operator: op, Value: "call"}
		if op == "in" {
			rule.Value = []any{"call", "email"}
		}
		probe := domain.ReportConfig{
			Chart:     domain.ReportChartBar,
			GroupBy:   &domain.ReportGroupBy{Field: "user_id"},
			Aggregate: &domain.ReportAggregate{Fn: "count"},
			Filters:   &domain.ReportFilterGroup{Op: "AND", Rules: []domain.ReportFilterRule{rule}},
		}
		got, _, err := buildReportSQL(activityRef(), activity.Catalog(), probe, testOrgID,
			reportScope{Scope: domain.DataScopeAll, UserID: testUserID})
		if err != nil {
			t.Fatalf("operator %q failed to compile: %v", op, err)
		}
		if strings.Contains(got, "activities.type") && !strings.Contains(got, "(activities.type)::text") {
			t.Errorf("operator %q reads the enum column uncast — Postgres will reject it:\n%s", op, got)
		}
	}

	task := domain.ReportOnlyObjectBySlug("task")
	if task == nil {
		t.Fatal("task descriptor missing")
	}
	taskCfg := domain.ReportConfig{
		Chart:     domain.ReportChartBar,
		GroupBy:   &domain.ReportGroupBy{Field: "assigned_to"},
		Aggregate: &domain.ReportAggregate{Fn: "count"},
		Filters: &domain.ReportFilterGroup{
			Op:    "AND",
			Rules: []domain.ReportFilterRule{{Field: "completed_at", Operator: "is_not_empty"}},
		},
	}
	q, _, err = buildReportSQL(taskRef(), task.Catalog(), taskCfg, testOrgID,
		reportScope{Scope: domain.DataScopeOwn, UserID: testUserID})
	if err != nil {
		t.Fatalf("tasks-completed-per-rep failed to compile: %v", err)
	}
	if !strings.Contains(q, "tasks.assigned_to") || !strings.Contains(q, "tasks.completed_at") {
		t.Errorf("unexpected SQL:\n%s", q)
	}
}

func TestBuildReportSQL_ScalarKPI(t *testing.T) {
	cfg := domain.ReportConfig{
		Chart:     domain.ReportChartKPI,
		Aggregate: &domain.ReportAggregate{Fn: "sum", Field: "value"},
	}
	q, _, err := buildReportSQL(dealRef(), dealCatalog(), cfg, testOrgID, reportScope{Scope: domain.DataScopeAll, UserID: uuid.Nil})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	want := "SELECT COALESCE(SUM(deals.value), 0) AS agg_value, COUNT(*) AS row_count FROM deals WHERE deals.org_id = ? AND deals.deleted_at IS NULL"
	if q != want {
		t.Errorf("query mismatch:\n got: %s\nwant: %s", q, want)
	}
}

func TestBuildReportSQL_TableMode(t *testing.T) {
	cfg := domain.ReportConfig{
		Chart:   domain.ReportChartTable,
		Columns: []string{"title", "value", "priority"},
		Sort:    &domain.ReportSort{By: "value", Dir: "desc"},
		Limit:   5000, // above cap → clamped
	}
	q, _, err := buildReportSQL(dealRef(), dealCatalog(), cfg, testOrgID, reportScope{Scope: domain.DataScopeAll, UserID: uuid.Nil})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	want := `SELECT deals.id AS "id", deals.title AS "title", deals.value AS "value", deals.custom_fields->>'priority' AS "priority" ` +
		"FROM deals WHERE deals.org_id = ? AND deals.deleted_at IS NULL ORDER BY deals.value DESC NULLS LAST LIMIT 1000"
	if q != want {
		t.Errorf("query mismatch:\n got: %s\nwant: %s", q, want)
	}
}

func TestBuildReportSQL_GroupLimitClamped(t *testing.T) {
	cfg := domain.ReportConfig{
		Chart:     domain.ReportChartBar,
		GroupBy:   &domain.ReportGroupBy{Field: "stage"},
		Aggregate: &domain.ReportAggregate{Fn: "count"},
		Limit:     999,
	}
	q, _, err := buildReportSQL(dealRef(), dealCatalog(), cfg, testOrgID, reportScope{Scope: domain.DataScopeAll, UserID: uuid.Nil})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.HasSuffix(q, "LIMIT 100") {
		t.Errorf("group limit not clamped to %d: %s", domain.MaxReportGroups, q)
	}
}

func TestBuildReportSQL_EveryOperator(t *testing.T) {
	cases := []struct {
		name     string
		field    string
		operator string
		value    any
		wantSQL  string // substring that must appear in the WHERE
		wantErr  bool
	}{
		{"eq text", "title", "eq", "Acme", "deals.title = ?", false},
		{"neq text", "title", "neq", "Acme", "deals.title IS DISTINCT FROM ?", false},
		{"contains", "title", "contains", "acme", "deals.title ILIKE ?", false},
		{"not_contains", "title", "not_contains", "acme", "deals.title NOT ILIKE ?", false},
		{"starts_with", "title", "starts_with", "A", "deals.title ILIKE ?", false},
		{"ends_with", "title", "ends_with", "Z", "deals.title ILIKE ?", false},
		{"gt number", "value", "gt", float64(10), "deals.value > ?", false},
		{"gte number", "value", "gte", float64(10), "deals.value >= ?", false},
		{"lt number", "value", "lt", float64(10), "deals.value < ?", false},
		{"lte number", "value", "lte", float64(10), "deals.value <= ?", false},
		{"in select", "priority", "in", []any{"low", "high"}, "IN (?, ?)", false},
		{"not_in relation", "stage", "not_in", []any{"a0000000-0000-0000-0000-000000000000"}, "IS NULL OR deals.stage_id NOT IN (?)", false},
		{"is_empty text col", "title", "is_empty", nil, "(deals.title IS NULL OR deals.title = '')", false},
		{"is_not_empty text col", "title", "is_not_empty", nil, "(deals.title IS NOT NULL AND deals.title <> '')", false},
		{"is_empty number col", "value", "is_empty", nil, "deals.value IS NULL", false},
		{"eq bool", "is_won", "eq", true, "deals.is_won = ?", false},
		{"date gt", "closed_at", "gt", "2026-01-01", "deals.closed_at > ?", false},
		// Type gating: text ops against non-text columns are rejected.
		{"contains on number", "value", "contains", "1", "", true},
		{"contains on relation", "stage", "contains", "x", "", true},
		{"gt on text", "title", "gt", "A", "", true},
		{"unknown operator", "title", "regex", ".*", "", true},
		{"unknown field", "nope", "eq", "x", "", true},
		{"number wants number", "value", "eq", "not-a-number", "", true},
		{"bool wants bool", "is_won", "eq", "maybe", "", true},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			cfg := domain.ReportConfig{
				Chart:     domain.ReportChartBar,
				Filters:   &domain.ReportFilterGroup{Op: "AND", Rules: []domain.ReportFilterRule{{Field: tc.field, Operator: tc.operator, Value: tc.value}}},
				GroupBy:   &domain.ReportGroupBy{Field: "stage"},
				Aggregate: &domain.ReportAggregate{Fn: "count"},
			}
			q, _, err := buildReportSQL(dealRef(), dealCatalog(), cfg, testOrgID, reportScope{Scope: domain.DataScopeAll, UserID: uuid.Nil})
			if tc.wantErr {
				if err == nil {
					t.Fatalf("expected error, got query: %s", q)
				}
				return
			}
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}
			if !strings.Contains(q, tc.wantSQL) {
				t.Errorf("query %q does not contain %q", q, tc.wantSQL)
			}
		})
	}
}

func TestBuildReportSQL_NestedGroupsAndOr(t *testing.T) {
	cfg := domain.ReportConfig{
		Chart: domain.ReportChartBar,
		Filters: &domain.ReportFilterGroup{
			Op: "AND",
			Rules: []domain.ReportFilterRule{
				{Field: "is_won", Operator: "eq", Value: false},
				{Op: "OR", Rules: []domain.ReportFilterRule{
					{Field: "value", Operator: "gt", Value: float64(1000)},
					{Field: "priority", Operator: "eq", Value: "high"},
				}},
			},
		},
		GroupBy:   &domain.ReportGroupBy{Field: "stage"},
		Aggregate: &domain.ReportAggregate{Fn: "count"},
	}
	q, args, err := buildReportSQL(dealRef(), dealCatalog(), cfg, testOrgID, reportScope{Scope: domain.DataScopeAll, UserID: uuid.Nil})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(q, "(deals.is_won = ? AND (deals.value > ? OR deals.custom_fields->>'priority' = ?))") {
		t.Errorf("nested group SQL wrong: %s", q)
	}
	if len(args) != 4 { // org + three filter values
		t.Errorf("args = %v", args)
	}
}

func TestBuildReportSQL_DepthAndRuleCaps(t *testing.T) {
	// Depth: nest 6 levels of groups.
	deep := domain.ReportFilterRule{Field: "title", Operator: "eq", Value: "x"}
	for i := 0; i < 6; i++ {
		deep = domain.ReportFilterRule{Op: "AND", Rules: []domain.ReportFilterRule{deep}}
	}
	cfg := domain.ReportConfig{
		Chart:     domain.ReportChartBar,
		Filters:   &domain.ReportFilterGroup{Op: "AND", Rules: []domain.ReportFilterRule{deep}},
		GroupBy:   &domain.ReportGroupBy{Field: "stage"},
		Aggregate: &domain.ReportAggregate{Fn: "count"},
	}
	if _, _, err := buildReportSQL(dealRef(), dealCatalog(), cfg, testOrgID, reportScope{Scope: domain.DataScopeAll, UserID: uuid.Nil}); err == nil {
		t.Error("expected depth-cap error")
	}

	// Rules: 51 leaves.
	var rules []domain.ReportFilterRule
	for i := 0; i < 51; i++ {
		rules = append(rules, domain.ReportFilterRule{Field: "title", Operator: "eq", Value: "x"})
	}
	cfg.Filters = &domain.ReportFilterGroup{Op: "OR", Rules: rules}
	if _, _, err := buildReportSQL(dealRef(), dealCatalog(), cfg, testOrgID, reportScope{Scope: domain.DataScopeAll, UserID: uuid.Nil}); err == nil {
		t.Error("expected rule-cap error")
	}
}

func TestBuildReportSQL_BucketWhitelist(t *testing.T) {
	cfg := domain.ReportConfig{
		Chart:     domain.ReportChartBar,
		GroupBy:   &domain.ReportGroupBy{Field: "closed_at", Bucket: "millennium'); DROP TABLE deals;--"},
		Aggregate: &domain.ReportAggregate{Fn: "count"},
	}
	if _, _, err := buildReportSQL(dealRef(), dealCatalog(), cfg, testOrgID, reportScope{Scope: domain.DataScopeAll, UserID: uuid.Nil}); err == nil {
		t.Error("expected bucket whitelist error")
	}
	// Bucket on a non-date field is rejected too.
	cfg.GroupBy = &domain.ReportGroupBy{Field: "stage", Bucket: "month"}
	if _, _, err := buildReportSQL(dealRef(), dealCatalog(), cfg, testOrgID, reportScope{Scope: domain.DataScopeAll, UserID: uuid.Nil}); err == nil {
		t.Error("expected bucket-on-non-date error")
	}
}

// Injection attempts: hostile identifiers can only arrive via a poisoned
// catalog entry (the config path is closed by the unknown-field check); the
// builder still refuses them.
func TestBuildReportSQL_RejectsHostileIdentifiers(t *testing.T) {
	badCatalog := []domain.ReportField{
		{Key: "evil", Type: "text", Column: `title" FROM users;--`},
	}
	cfg := domain.ReportConfig{
		Chart:     domain.ReportChartBar,
		GroupBy:   &domain.ReportGroupBy{Field: "evil"},
		Aggregate: &domain.ReportAggregate{Fn: "count"},
	}
	if _, _, err := buildReportSQL(dealRef(), badCatalog, cfg, testOrgID, reportScope{Scope: domain.DataScopeAll, UserID: uuid.Nil}); err == nil {
		t.Error("expected hostile column to be rejected")
	}

	badJSON := []domain.ReportField{
		{Key: "evil2", Type: "text", JSONKey: `x'||(SELECT password_hash FROM users LIMIT 1)||'`},
	}
	cfg.GroupBy = &domain.ReportGroupBy{Field: "evil2"}
	if _, _, err := buildReportSQL(dealRef(), badJSON, cfg, testOrgID, reportScope{Scope: domain.DataScopeAll, UserID: uuid.Nil}); err == nil {
		t.Error("expected hostile JSON key to be rejected")
	}
}

func TestBuildReportSQL_AggregateGating(t *testing.T) {
	mk := func(fn, field string) domain.ReportConfig {
		return domain.ReportConfig{
			Chart:     domain.ReportChartKPI,
			Aggregate: &domain.ReportAggregate{Fn: fn, Field: field},
		}
	}
	// sum on a text field → rejected.
	if _, _, err := buildReportSQL(dealRef(), dealCatalog(), mk("sum", "title"), testOrgID, reportScope{Scope: domain.DataScopeAll, UserID: uuid.Nil}); err == nil {
		t.Error("expected sum-on-text error")
	}
	// unknown fn → rejected.
	if _, _, err := buildReportSQL(dealRef(), dealCatalog(), mk("median", "value"), testOrgID, reportScope{Scope: domain.DataScopeAll, UserID: uuid.Nil}); err == nil {
		t.Error("expected unknown-fn error")
	}
	// count_distinct works on any type.
	q, _, err := buildReportSQL(dealRef(), dealCatalog(), mk("count_distinct", "stage"), testOrgID, reportScope{Scope: domain.DataScopeAll, UserID: uuid.Nil})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(q, "COUNT(DISTINCT deals.stage_id)") {
		t.Errorf("count_distinct SQL wrong: %s", q)
	}
}

func TestBuildReportSQL_EmptyInList(t *testing.T) {
	mk := func(op string) domain.ReportConfig {
		return domain.ReportConfig{
			Chart:     domain.ReportChartBar,
			Filters:   &domain.ReportFilterGroup{Op: "AND", Rules: []domain.ReportFilterRule{{Field: "priority", Operator: op, Value: []any{}}}},
			GroupBy:   &domain.ReportGroupBy{Field: "stage"},
			Aggregate: &domain.ReportAggregate{Fn: "count"},
		}
	}
	q, _, err := buildReportSQL(dealRef(), dealCatalog(), mk("in"), testOrgID, reportScope{Scope: domain.DataScopeAll, UserID: uuid.Nil})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(q, "(FALSE)") {
		t.Errorf("empty in-list should collapse to FALSE: %s", q)
	}
	q, _, err = buildReportSQL(dealRef(), dealCatalog(), mk("not_in"), testOrgID, reportScope{Scope: domain.DataScopeAll, UserID: uuid.Nil})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(q, "(TRUE)") {
		t.Errorf("empty not-in should collapse to TRUE: %s", q)
	}
}

func TestBuildReportSQL_LikeWildcardsEscaped(t *testing.T) {
	cfg := domain.ReportConfig{
		Chart:     domain.ReportChartBar,
		Filters:   &domain.ReportFilterGroup{Op: "AND", Rules: []domain.ReportFilterRule{{Field: "title", Operator: "contains", Value: "50%_off"}}},
		GroupBy:   &domain.ReportGroupBy{Field: "stage"},
		Aggregate: &domain.ReportAggregate{Fn: "count"},
	}
	_, args, err := buildReportSQL(dealRef(), dealCatalog(), cfg, testOrgID, reportScope{Scope: domain.DataScopeAll, UserID: uuid.Nil})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	// args: org, pattern
	pattern, _ := args[len(args)-1].(string)
	if pattern != `%50\%\_off%` {
		t.Errorf("pattern = %q, want %q", pattern, `%50\%\_off%`)
	}
}

func TestBuildReportSQL_TableModeUnknownColumnRejected(t *testing.T) {
	cfg := domain.ReportConfig{
		Chart:   domain.ReportChartTable,
		Columns: []string{"title", "password_hash"},
	}
	if _, _, err := buildReportSQL(dealRef(), dealCatalog(), cfg, testOrgID, reportScope{Scope: domain.DataScopeAll, UserID: uuid.Nil}); err == nil {
		t.Error("expected unknown column to be rejected")
	}
}
