package automation

import (
	"testing"

	"github.com/google/uuid"
	"pgregory.net/rapid"
)

// run_now_classify_pbt_test.go holds the property-based test for Run Now request
// classification. It exercises classifyRunNowRequest (run_now.go) across the full
// cross-product of {empty, valid UUID, invalid string} for contact_id and deal_id,
// drawn independently, asserting the accept/reject rule the spec requires.

// idCategory labels the three input classes a contact_id / deal_id field can fall into.
type idCategory string

const (
	catEmpty   idCategory = "empty"   // the field is the empty string
	catValid   idCategory = "valid"   // the field is a syntactically valid UUID
	catInvalid idCategory = "invalid" // the field is a non-empty, non-UUID string
)

// drawID draws an identifier field independently from {empty, valid UUID, invalid
// string} and returns both the generated value and the category it belongs to so the
// assertion can compute the expected classification deterministically.
func drawID(t *rapid.T, label string) (value string, category idCategory) {
	category = rapid.SampledFrom([]idCategory{catEmpty, catValid, catInvalid}).Draw(t, label+"_category")
	switch category {
	case catEmpty:
		return "", catEmpty
	case catValid:
		// Build a valid UUID from rapid-generated bytes so the case is reproducible
		// and shrinkable (uuid.NewString would be non-deterministic).
		b := rapid.SliceOfN(rapid.Byte(), 16, 16).Draw(t, label+"_uuidBytes")
		u, err := uuid.FromBytes(b)
		if err != nil {
			t.Fatalf("uuid.FromBytes failed for 16 bytes: %v", err)
		}
		return u.String(), catValid
	default: // catInvalid
		// Any non-empty string that does NOT parse as a UUID. Random strings are
		// essentially never valid UUIDs, so the filter rejects almost nothing.
		s := rapid.String().Filter(func(s string) bool {
			if s == "" {
				return false
			}
			_, err := uuid.Parse(s)
			return err != nil
		}).Draw(t, label+"_invalid")
		return s, catInvalid
	}
}

// TestProp_ClassifyRunNowRequest verifies Property 1 across 100+ generated inputs.
//
// Feature: run-now-workflow, Property 1: Request body classification
//
// For any request body with optional contact_id and deal_id string fields, the
// classifier returns contact-targeted exactly when contact_id is the only non-empty
// field and is a valid UUID, returns deal-targeted exactly when deal_id is the only
// non-empty field and is a valid UUID, and otherwise rejects the request as invalid
// (both present, neither present, or a present identifier that is not a valid UUID).
//
// Validates: Requirements 2.1, 2.2, 2.3, 2.4, 2.5
func TestProp_ClassifyRunNowRequest(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		contactID, contactCat := drawID(t, "contact_id")
		dealID, dealCat := drawID(t, "deal_id")

		req := RunNowRequest{ContactID: contactID, DealID: dealID}
		kind, entityID, err := classifyRunNowRequest(req)

		// Expected classification, derived independently from the input categories.
		expectContact := contactCat == catValid && dealCat == catEmpty
		expectDeal := dealCat == catValid && contactCat == catEmpty

		switch {
		case expectContact:
			// Req 2.1: contact_id is the only valid non-empty id => contact-targeted.
			if err != nil {
				t.Fatalf("expected contact-targeted, got error: %v (contact=%q deal=%q)", err, contactID, dealID)
			}
			if kind != "contact" {
				t.Fatalf("expected kind %q, got %q (contact=%q deal=%q)", "contact", kind, contactID, dealID)
			}
			if want, _ := uuid.Parse(contactID); entityID != want {
				t.Fatalf("expected entityID %v, got %v", want, entityID)
			}

		case expectDeal:
			// Req 2.2: deal_id is the only valid non-empty id => deal-targeted.
			if err != nil {
				t.Fatalf("expected deal-targeted, got error: %v (contact=%q deal=%q)", err, contactID, dealID)
			}
			if kind != "deal" {
				t.Fatalf("expected kind %q, got %q (contact=%q deal=%q)", "deal", kind, contactID, dealID)
			}
			if want, _ := uuid.Parse(dealID); entityID != want {
				t.Fatalf("expected entityID %v, got %v", want, entityID)
			}

		default:
			// Req 2.3 (both), 2.4 (neither), 2.5 (single present id is invalid):
			// every other combination must be rejected with an error, and a rejected
			// body must surface no kind and no entity id (no run path is entered).
			if err == nil {
				t.Fatalf("expected error for contactCat=%s dealCat=%s, got kind=%q entityID=%v (contact=%q deal=%q)",
					contactCat, dealCat, kind, entityID, contactID, dealID)
			}
			if kind != "" {
				t.Fatalf("expected empty kind on rejection, got %q", kind)
			}
			if entityID != uuid.Nil {
				t.Fatalf("expected uuid.Nil entityID on rejection, got %v", entityID)
			}
		}
	})
}
