package automation

import (
	"testing"

	"pgregory.net/rapid"
)

// Feature: run-now-workflow, Property 4: Idempotency bypass via unique run keys
//
// For any number N (>= 2) of confirmed Run Now invocations that share the same
// workflow, entity, and minute, the idempotency keys generated by
// newRunNowIdempotencyKey() (used by Engine.RunWorkflowNow) are pairwise distinct.
// Because newRunNowIdempotencyKey() takes no arguments, the shared logical context is
// irrelevant to the generated key by construction — the point of this property is that
// even when the logical context is identical, the keys still differ, so each confirmed
// request inserts a new Workflow_Run rather than being de-duplicated against a prior
// natural or manual trigger.
//
// Validates: Requirements 6.5
func TestRunNowIdempotencyKeyUniqueness_Property(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		// N >= 2 invocations sharing an identical workflow/entity/minute context. The
		// shared context does not feed into the key (the function is nullary); we draw N
		// only to exercise a range of invocation counts.
		n := rapid.IntRange(2, 256).Draw(t, "n")

		seen := make(map[string]struct{}, n)
		for i := 0; i < n; i++ {
			key := newRunNowIdempotencyKey()
			seen[key] = struct{}{}
		}

		// Pairwise distinct <=> the set of keys has exactly N members.
		if len(seen) != n {
			t.Fatalf("expected %d pairwise-distinct idempotency keys, got %d distinct (duplicates generated)", n, len(seen))
		}
	})
}
